name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # Set Node.js Version
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "pip"
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install dependencies
        working-directory: starter/backend
        run: pip install --upgrade pip

      - name: Run lint
        working-directory: starter/backend
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "pip"
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install dependencies
        working-directory: starter/backend
        run: pip install --upgrade pip

      - name: Run Test
        working-directory: starter/frontend
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    if: ${{ always() }}
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "pip"
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install dependencies
        working-directory: starter/backend
        run: pip install --upgrade pip

      - name: Build App
        working-directory: starter/backend
        run: |
          echo "Building... ${{github.sha}}"
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://localhost:3000/ --tag= ${{github.sha}}:latest .
