name: frontend ci workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # Set Node.js Version
  NODE_VERSION: "18"

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install dependencies
        run: cd ./starter/frontend && npm ci

      - name: Run lint
        run: cd ./starter/frontend && npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   continue-on-error: false
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{env.NODE_VERSION}}
  #         cache: "npm"

  #     - name: Install dependencies
  #       working-directory: starter/frontend
  #       run: npm ci

  #     - name: Run Test
  #       working-directory: starter/frontend
  #       run: npm run test

  # build:
  #   runs-on: ubuntu-latest
  #   continue-on-error: false
  #   if: ${{ always() }}
  #   needs: [lint, test]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{env.NODE_VERSION}}
  #         cache: "npm"

  #     - name: Install dependencies
  #       working-directory: starter/frontend
  #       run: npm ci

  #     - name: Complete Build
  #       working-directory: starter/frontend
  #       run: echo "Building Completed..."
