name: frontend ci workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # Set Node.js Version
  NODE_VERSION: "20.7.0"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        run: cd starter/front && npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run Test
        working-directory: starter/frontend
        run: cd starter/front && npm run test

  build:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Complete Build
        working-directory: starter/frontend
        run: echo "Building Completed..."
