name: Frontend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # Set Node.js Version
  NODE_VERSION: "20.7.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run Test
        working-directory: starter/frontend
        run: npm run test

  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    if: ${{ always() }}
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Build App
        working-directory: starter/frontend
        run: |
          echo "Building... ${{github.run_id}}"
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://localhost:3000/ --tag=${{github.run_id}}:latest .
          docker run ${{github.run_id}} -p 3000:3000
